### ISSUE TITLE
2.0.0 release contents

### ISSUE THREAD

**Issue by scsper** [amasad/sane#102]
I see a 2.0.0 release on npm, but I don't see a release in GitHub.  Because it's a major version upgrade, I'm wondering what breaking changes there are to see if I can upgrade to it.  

Thanks!

**Comment by amasad** [comment]
Oops forgot to push -- here we go: https://github.com/amasad/sane/releases/tag/v2.0.0

It's basically using fsevents optional dependency

**Comment by scsper** [comment]
thanks.  when will this change be released?  https://github.com/amasad/sane/commit/3b6e45bed10c5842aaf22ad3f651f570c50de519

**Comment by amasad** [comment]
already went out with 2.0
