### ISSUE TITLE
`micromatch.some` is not a function

### ISSUE THREAD

**Issue by benderTheCrime** [amasad/sane#116]
Hey, I'm getting this error from inside of my react-native (metro) bundler:

`ERROR  micromatch.some is not a function`

I have three installations of sane in my graph, all of which are 2.5.0. 

When I do an `npm ls` on micromatch, the dependency causing the problem, I see that sane directly depends on 2.5.0, but that other dependencies do depend on a 3.x version of the same module. I'm using NodeJS@8.10.

The error itself is coming from this function:

```javascript
exports.isFileIncluded = function(globs, dot, doIgnore, relativePath) {
  if (doIgnore(relativePath)) {
    return false;
  }
  return globs.length
    ? micromatch.some(relativePath, globs, { dot: dot })
    : dot || micromatch.some(relativePath, '**/*');
};
```

Temporarily, I've fixed it by just returning `true`.

Please let me know if there is anything else I can do to help!

**Comment by benderTheCrime** [comment]
For now, I've just downgraded react-native. This seems not to be the only issue associated with that release, which for perpetuity is react-native@0.55.x

**Comment by stefanpenner** [comment]
@benderTheCrime does react native maybe bundle dependencies? there may be an issue with how they bundle them, specifically maybe they bundle the wrong deps.

So far, I don't see any issues with this project itself. Rather it seems like something may be installing the wrong micro-match. What do you think?

**Comment by benderTheCrime** [comment]
For sure, react-native has it's own dependency bundler. Rather, I _should_ say Facebook has it's own dependency bundler and react-native uses it. Found here: https://github.com/facebook/metro

I think that that's likely true and we can consider this closed as either being a react-native or micromatch based issue.

**Comment by stefanpenner** [comment]
@benderTheCrime thanks. If further issues arise, don't hesitate to raise them here :)
