### ISSUE TITLE
Update `fsevents` dep

### ISSUE THREAD

**Issue by chaffeqa** [amasad/sane#117]
[fsevents@1.2.3](https://github.com/strongloop/fsevents/releases/tag/v1.2.3) contains a fix for nodev10.  This prevents any installation of [jest since it tries to pull in sane@^2.0.0](https://github.com/facebook/jest/blob/84b17fb59c1d9fd7f964b5f2bfd9d7e2b898f89a/packages/jest-haste-map/package.json#L17) and then [finds the non-optional fsevents](https://github.com/facebook/jest/blob/3ce87434570d23be061648162488ca5599e40651/packages/jest-haste-map/src/index.js#L651), which blows up.

I'm also opening a issue in jest refering to this (since I think the updating to sane@^2.5.0 will make it trully optional/opt-in-only).

I think both groups should be aware

**Comment by SimenB** [comment]
It's useful to bump as doing deep upgrades is not the easiest, especially if current versions are important to keep for other deps.

But it _is_ possible for consumers to update themselves

**Comment by stefanpenner** [comment]
> It's useful to bump as doing deep upgrades is not the easiest, especially if current versions are important to keep for other deps.

isn't the fix simply reinstalling + deleting lock files?

**Comment by stefanpenner** [comment]
Not that I actually don't agree, we should just bump. It comes at little risk, I want to just understand the above ^.

**Comment by chaffeqa** [comment]
Honestly I don't think I arrived at a suggest-able solution.  It's a pretty intricate and deep problem, in lieu of a quick solution coming to mind, I just decided to log it to relevent parties.

My of-the-top-of-the-head solution would be:
* Bump the `fsevents` optional dep to `^1.2.3`, and release an appropriate semvar version update which if I'm not mistaken, is patch level since updating `sane` in a project won't automatically update the `fsevents`

I may be wrong, either way though my hunch is the larger fix is https://github.com/facebook/jest/issues/6123

**Comment by chaffeqa** [comment]
👍  thanks for the quick turnaround!

**Comment by stefanpenner** [comment]
released as v2.5.1 🎉

**Comment by stefanpenner** [comment]
> 👍 thanks for the quick turnaround!

Absolutely!

**Comment by SimenB** [comment]
>isn't the fix simply reinstalling + deleting lock files?

Yes, if it's acceptable to dump the lock files - that's not a given 🙂 We ended up bumping some istanbul deps in Jest even though they were in semver range as the upgrade internally at FB apparently was difficult
