### ISSUE TITLE
Invalid tag name "sane@2.2.0": Tags may not have any characters that encodeURIComponent encodes.

### ISSUE THREAD

**Issue by a-x-** [amasad/sane#138]
I don't use sane directly and I has not updated any packages targetly,
but today npm i becomes broken

npm 6.8.0
node v11.10.1

package-json: 
- **dependencies.sane**
```json5
    {
      "version": "2.2.0",
      "resolved": "https://registry.npmjs.org/svgo-loader/-/svgo-loader-2.2.0.tgz",
      "integrity": "sha512-AtIy4kmUQc1zo+QK3ZFvRrULRZAhUC63cLJxdVo1cONZ9WeYAkySUlaB05uZKKcYpsTb/9tDsBSXMab3/0QWtw==",
      "dev": true,
      "requires": {
        "js-yaml": "^3.12.0",
        "loader-utils": "^1.0.3"
      },
      // ...
    }
```
- **dependencies["jest-haste-map"].requires.sane**:  "^2.0.0"

**Comment by stefanpenner** [comment]
@a-x- very strange, but I don't think there is anything wrong on our end.

Closing, but will gladly reopen if someone can suggest what might be wrong here.
