### ISSUE TITLE
Why the sane@3.1.0 don't support node 9.*.* 

### ISSUE THREAD

**Issue by howel52** [amasad/sane#139]
I was install sane@3.1.10 in window 10 and node 9.10.1

Got a error message:

> sane@3.1.0: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*". Got "9.10.1"

**Comment by stefanpenner** [comment]
correct, in general we do not support versions of node that node itself doesn’t support. See: https://github.com/nodejs/Release for which versions are officially supported and there timelines.

**Comment by howel52** [comment]
> correct, in general we do not support versions of node that node itself doesn’t support. See: https://github.com/nodejs/Release for which versions are officially supported and there timelines.

Thanks 😄
