### ISSUE TITLE
Watching file recursively

### ISSUE THREAD

**Issue by tbhaxor** [amasad/sane#140]
I am using the sane library with the following file structure
```
project
-- src/
---- index.js
-- build/
---- index.js
package.json
```

i want sane to watch files in all subdirectory

**Comment by stefanpenner** [comment]
@tbhaxor yes, what you describe is how sane works today. Can you share an example of how this doesn't work? (My projects that use sane also depend on the functionality you describe)

**Comment by tbhaxor** [comment]
Earlier i was using `chokidar` and there the used GLOB pattern and array of files/directories to be ignored.

The glob pattern i am using in sane is `*/*.ts` to ignore all typescript files in the directory and subdirectory

**Comment by stefanpenner** [comment]
@tbhaxor would the `ignored` option handle this scenario? If not, can you help me understand why?

**Comment by tbhaxor** [comment]
Actually its ignoring only TS files in `pwd` and my full directory structure is
```
project
-- src
---- server
------ index.ts
------ routes
-------- libs.ts
-------- apis.ts
------ models
-------- libst.ts
-------- apist.ts
---- engine.ts
---- maker.ts
---- globs.ts
---- utils .ts
```

and the current patteren `*/*.ts` is watching `index.ts` `maker.ts` `globs.ts` `utils.ts` files only

**Comment by tbhaxor** [comment]
@stefanpenner any suggestion ?

**Comment by tbhaxor** [comment]
Closing this issue, since no one is showing interest
