### ISSUE TITLE
Support for more Node.js versions

### ISSUE THREAD

**Issue by mhipszki** [amasad/sane#149]
`sane@4.1.0` currently supports former and current LTS versions of Node.js: `6.x`, `8.x` and `10.x`+

This puts a restriction on dependant projects to only support these versions but no other versions as the installation of dependencies will fail when the actual version of Node.js does not exactly match these versions.

I wonder why `sane` does not support e.g. `7.x` or `9.x` versions of Node.js?

[My library](https://github.com/mhipszki/eslint-formatter-summary) currently supports Node.js version `4.x`+ but needs its dependencies to be upgraded now due to security issues with some of the sub-dependecies.

Users of my library will lose support in case they are not on "even" versions of Node.js in case I upgrade e.g. `jest` to latest which relies on `sane`.

I'd like to understand the reasons behind this restriction and if it would be possible to extend the supported Node.js versions for "odd" major version too?

**Comment by stefanpenner** [comment]
The idea is to only support versions of node which are still under support by node itself.

See: https://github.com/nodejs/Release for specifics on node support policy.

Also note, When changes are made to the engines property we also do a major version bump. This ensures our support alignment changes are semver compatible.
