### ISSUE TITLE
Consider dropping `node@6`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [amasad/sane#151]
Mostly so `micromatch` can be bumped.  `micromatch@3` has some notable performance and size penalties but `micromatch@4` requires `node>=8`.  This'd probably close #143 and make #147 a little more straightforward.  `jest` is also [currently looking to drop `node@6` support for the next major](https://github.com/facebook/jest/pull/8455), so it'd need this to be done to fully feel the effects.

I'll file a PR if this is acceptable.

**Comment by stefanpenner** [comment]
I'm going to drop 6,8, supporting 10 + >= 12 as node 8 EOLs shortly.

**Comment by COScholl** [comment]
Changes made by @stefanpenner have been merged do drop support for older versions of node.
