### ISSUE TITLE
High severity vulnerability detected in sane dependencies

### ISSUE THREAD

**Issue by kamalyzl** [amasad/sane#163]
A security assessment was performed and vulnerabilities were found to dependency sane

 
It is requested to update from version "execa": "^1.0.0" to "execa": "^4.1.0"
being version 4.1.0 the last stable

reference: https://github.com/sindresorhus/execa/tags

**Comment by COScholl** [comment]
sane@4.1.0 is now deprecated in favor of sane@5.0.1 with dep execa@4.0.0
