### ISSUE TITLE
High Vulnerability is found in the dependency.

### ISSUE THREAD

**Issue by karthiksubbiah1983** [amasad/sane#165]
High vulnerability is found in below path.
https://snyk.io/test/npm/sane/4.1.0

└─┬ ember-cli@3.24.0
└─┬ sane@4.1.0
└─┬ micromatch@3.1.10
└─┬ snapdragon@0.8.2
└─┬ base@0.11.2
└── cache-base@1.0.1

**Comment by COScholl** [comment]
@karthiksubbiah1983 sane@4.1.0 is now deprecated in favor of sane@5.0.1
