### ISSUE TITLE
node error: FSEventStreamStart: register_with_server

### ISSUE THREAD

**Issue by matthewmueller** [amasad/sane#25]
Running into this weird error on node 0.10.22:

![error](https://i.cloudup.com/kH3t7rdA2Q.png)

Using it like this: 

``` js
// file watching
this.sane = sane(root)
  .on('change', this.change.bind(this));
```

**Comment by stefanpenner** [comment]
I believe we can close this now. v0.12 is EOL, and watchman support is baked in
