### ISSUE TITLE
ENOENT on emacs interlock files.

### ISSUE THREAD

**Issue by SohumB** [amasad/sane#37]
I'm using `sane` + `watchman` (via `ember-cli`) to watch a directory. As I edit files in those directories, emacs creates ["interlock" symlinks](http://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html) with weird contents; this is what `ls` reports on one of them:

```
lrwxrwxrwx 1 sohum sohum    38 Dec 10 15:34 .#menus-test.js -> sohum@diurnal.nsb0.net.7730:1418204054
```

When these files are deleted, `sane` crashes on an ENOENT error. 

The error appears to be coming from `WatchmanWatcher.prototype.handleFileChange`, as it seems to be treating the stat error as a failure instead of a deletion.

Thanks!

**Comment by wez** [comment]
Watchman doesn't care what the symlink points to.  It will report `.#menus-test.js` as existing because it exists in the filesystem even if the target of the symlink doesn't exist.  I think you should switch to `fs.lstat` instead of `fs.stat` so that you don't try to follow symlinks.
