### ISSUE TITLE
Allow a custom filter function instead of glob

### ISSUE THREAD

**Issue by callumlocke** [amasad/sane#41]
1. I want to be able to pass a custom function that examines filenames and returns true/false
2. I propose renaming the `glob` option to `filter` (and keeping `glob` as an alias, for back compatibility)

let me know if you agree with one or both of the above, and I'll PR!

**Comment by amasad** [comment]
Would love to pull, but let's make it a filter function in addition to glob, I don't like overloading the same arg with multiple types

**Comment by callumlocke** [comment]
ok :+1:

**Comment by stefanpenner** [comment]
We are still open for a pull request, but as this as this has gone stale I will close.
