### ISSUE TITLE
Can it be used with Command line ?

### ISSUE THREAD

**Issue by IbnSaeed** [amasad/sane#44]
I have to get it running as a task inside NPM build scripts.

If it possible ?

**Comment by amasad** [comment]
We can we add a cli program. Want to do it?

**Comment by m-allanson** [comment]
I've added a CLI (based on the cli script used by watch), which can be seen here: https://github.com/m-allanson/sane/commit/50bae5be5195de908a8e305030a2bf236c3e6028

I'm not sure how to write tests for it though.  Any ideas?  Locally I'm running OSX 10.10.3 and it all appears to work.

I can create a PR if it's something you'd consider merging in.

**Comment by IbnSaeed** [comment]
@m-allanson Thanks for CLI implementation. How does it work so far ?

Take a look at this https://github.com/tkellen/js-liftoff

**Comment by amasad** [comment]
@m-allanson Looks great! Please do send PR

**Comment by amasad** [comment]
published in v1.0.4
