### ISSUE TITLE
What's the difference to chokidar?

### ISSUE THREAD

**Issue by jzaefferer** [amasad/sane#45]
Diversity is good, fragmentation is bad. I'm wondering what the advantage of this package are over [chokidar](https://www.npmjs.com/package/chokidar), which seems pretty well maintained and, for now, much more popular. Maybe another `fs.watch` wrapper isn't actually needed? Or if it is, can you at least document the differences?

**Comment by amasad** [comment]
You can spot some of the differences in the first paragraph.

1. It's not simply an `fs.watch` wrapper, it supports multiple watch backends -- including and most importantly for us (facebook) -- [watchman](https://github.com/facebook/watchman) which is faster and a lot more reliable than chokidar.
2. Doesn't need a native component to work. Chokidar, without fsevents is really buggy and unreliable, try it.
3. I needed a ready event and the maintainer at that time refused to merge my PR https://github.com/paulmillr/chokidar/pull/103
4. Maybe recently chokidar became decent, when I wrote sane, it was very unreliable and buggy . Sane solved real issues for people in the ember-cli, component/duo communities and for us at facebook

**Comment by amasad** [comment]
we can continue discussing, I'm just closing because it's not actionable. Let me know if you have any thoughts on how/if we can consolidate. But to answer your main question, no, I didn't write this and maintain this because I have time to kill :)
