### ISSUE TITLE
optionally support `--no-save-state`

### ISSUE THREAD

**Issue by stefanpenner** [amasad/sane#48]
a watchman does not age-out watchers yet, some use-cases would prefer a restart to blow away watching state.

I suspect either this project of `fb-watchman` needs some tweaking to support this option.

**Comment by amasad** [comment]
so optionally do a `watch-del` on exit?

**Comment by stefanpenner** [comment]
no, I believe `--no-save-state` is a flag we can pass to watchman itself.

Honestly, i would love for these watchers to just actually age out. I am just looking for a short-term solution.

**Comment by stefanpenner** [comment]
Watchman I believe ages out watches now, we should be good.
