### ISSUE TITLE
Deprecate and favor chokidar

### ISSUE THREAD

**Issue by bucaran** [amasad/sane#52]
The title is just the nuts and bolts of the proposal, my suggestion is much more kind :smile: 

chokidar (followed closely by gaze) is probably the standard file watcher favored by the node community (at large). I think we can agree the benefits of having one package less to debug / browser for issues whenever a problem occurs.

`sane` is the watcher used by `ember-cli` so perhaps I should open an issue there instead, but I thought of asking here first and see what you think.

No ill intentions! 

Regards

**Comment by amasad** [comment]
It could've taken you fewer keystrokes to google if this was discussed before than typing the issue up :)
https://github.com/facebook/react-native/issues/628

**Comment by bucaran** [comment]
@amasad Oh, thanks! :smile:
