### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by flosse** [amasad/sane#57]
I'm using sane `v1.0.2` and want to upgrade to the newest version `v1.3.0`. As there is no changelog and nothing mentioned about semantic versioning, can you tell me if there are any braking changes?

**Comment by amasad** [comment]
Sorry I didn't maintain a changelog. I try to follow [semver](http://semver.org/). You can look at the commits between the releases to get an idea. There is a release note here for 1.1: https://github.com/amasad/sane/releases
And then other things has been to introduce a plugin system and bug fixes. Should be safe to upgrade.
