### ISSUE TITLE
"add" event on directories does not check glob patterns

### ISSUE THREAD

**Issue by tomccabe** [amasad/sane#58]
When committing to git while watching, the ALL_EVENT is fired on .git/objects and those files are wrongly acted upon (it also causes some recursive actions on my build folder...essentially my globs are ignored for some files). Removing line 314 of node_watcher.js solves this problem and I can't really see what that line is there for in the first place?

**Comment by amasad** [comment]
pass in `dot: false` which ignore dot files from the watch. See the readme.

**Comment by tomccabe** [comment]
I've already done that with no change in behavior.

**Comment by amasad** [comment]
that's strange, I don't see how listening on the event will cause the glob to be ignored. Feel free to debug and send me a patch if you find a solution

**Comment by tomccabe** [comment]
The only way to fix is to comment out line 314 of node_watcher.js. What's the reasoning behind emitting the "all" event? This line emits an event that is also picked up by my `change` handler.

**Comment by amasad** [comment]
You can just not listen to the `all` event. It's not a special event that will execute all handlers. It's a custom thing that could be useful if you're interested in all events and don't want to listen to everyone manually.

**Comment by tomccabe** [comment]
I was actually incorrect as I was debugging...PR #59 opened.
 #59

**Comment by tomccabe** [comment]
Steps to reproduce: 

1. start Sane watch
2. make a change
3. `git commit` change
4. `.git/objects/[dir]` will be acted upon by `ADD_EVENT` handler

This happens with other non-watched directories (i.e. a build dir), but is easy to reproduce with git commit
