### ISSUE TITLE
sane Node Watcher doesn't always close properly.

### ISSUE THREAD

**Issue by cpojer** [amasad/sane#60]
This problem came up as part of react-native and jest 0.9.

To repro: make node-haste use the NodeWatcher in jest's HasteResolver, see https://github.com/facebook/jest/blob/master/src/resolvers/HasteResolver.js#L23

Run any JS test on react-native. The tests will pass but afterwards the process won't exit and just hang. `end` is being called properly. Make sure not to use watchman, of course :)

Wanted to open this up here to track the issue. This has caused a few bumps on FB's test infra where watching was accidentally used and then timed out the processes. Ideally, even if watching is used there, the process should properly exit :)

**Comment by amasad** [comment]
Couldn't reproduce in isolation. Are you sure we're calling `.close()` (not end)?
Here is my test:

```js
var watcher = require('./')('./');
watcher.on('ready', function() {
  console.log('ready');
  setTimeout(function() {
    watcher.close();
  }, 1000);
});
```

I can try it on RN next week.

**Comment by cpojer** [comment]
yeah it never happened to me outside of this context. Internally the watcher was getting hung up by a lock file that I guess it couldn't access. Not sure what the problems were on travis or locally, it didn't throw (but maybe a promise swallowed it?).

**Comment by stefanpenner** [comment]
I tried to replicate myself, no luck. Will gladly reopen with reproduction, or at-least more bug reports suggesting this is a persistent issue.
