### ISSUE TITLE
Sane is insanely slow

### ISSUE THREAD

**Issue by Vanuan** [amasad/sane#66]
```
mkdir files_watched
for i in {1..1000}; do touch files_watched/$i; done
npm install sane
```
In node:

```
var sane = require('sane');
var files = (new Array(1000)).fill().map(function(_, i) { return (i + 1).toString() })
var time = Date.now();
var watcher = sane('.', { glob: files });
watcher.on('ready', function() {
  console.log((Date.now() - time)/1000 + " seconds elapsed");
});

```

Here's what is printed:

`22.705 seconds elapsed`

What's that? 22 seconds for 1000 files?
What if we just use `*` pattern?

```
var sane = require('sane');
var time = Date.now();
var watcher = sane('.', { glob: '*' });
watcher.on('ready', function() {
  console.log((Date.now() - time)/1000 + " seconds elapsed");
});
```

0.091 seconds elapsed

Wow, that's much better.

What's the case here?

**Comment by amasad** [comment]
For every file you have to test against the array of file patters you
matched that's o(n^2). To use similar words -- that's insanely dumb.

**Comment by amasad** [comment]
If you want to match against specific file names I suggest filtering the events instead
