### ISSUE TITLE
minimatch dependency is out of date

### ISSUE THREAD

**Issue by lookfirst** [amasad/sane#68]
```
│ └─┬ sane@1.3.4
│   └── minimatch@0.2.14
```

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by m-allanson** [comment]
FYI, here's the Node Security Project advisory: https://nodesecurity.io/advisories/118

**Comment by amasad** [comment]
trouble is minimatch has no changelog, no release notes, nothing. Not sure if we can release a patch

**Comment by amasad** [comment]
I looked at minimatch's readme and it hasn't changed in 4 years. It seems like all the changes are internal. Given that, I just released a patch so that existing users get the security fix.

**Comment by lookfirst** [comment]
Really? Where you looking? https://github.com/isaacs/minimatch

**Comment by lookfirst** [comment]
Too be fair, I don't see release notes or a changelog for sane either. ;-)

Anyway, thanks for the update.

**Comment by stefanpenner** [comment]
we use micromatch now
