### ISSUE TITLE
Consider separating CLI.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [amasad/sane#74]
The five most popular dependants of `sane`, [`jest-haste-map`](https://www.npmjs.com/package/jest-haste-map), [`jest-cli`](https://www.npmjs.com/package/jest-cli), [`ember-cli`](https://www.npmjs.com/package/ember-cli), [`react-native`](https://www.npmjs.com/package/react-native), and [`broccoli-sane-watcher`](https://www.npmjs.com/package/broccoli-sane-watcher) do not use the CLI.  It would reduce their dependency graphs to split `sane` into two packages, something like `sane` and `sane-cli`, or `sane` and `sane-core`.  Would something like this be considered?

**Comment by amasad** [comment]
This would relief them of 2 dependencies? I'm not sure it's worth it

**Comment by wtgtybhertgeghgtwtg** [comment]
Those two dependencies are about 50 KB together.  It may not be worth it, but I felt that it was worth suggesting.

**Comment by wtgtybhertgeghgtwtg** [comment]
This doesn't help my case at all, but this actually wouldn't get rid of those dependencies, since `watch` still depends on them.  I would love to help remove the dependency on `watch`, however.

**Comment by stefanpenner** [comment]
>  50 KB together

I think this is a small price to pay for keeping maintainership overhead low.
