### ISSUE TITLE
`add` without `change`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [amasad/sane#75]
Currently, creating and writing to a file in a watched directory with a method like `fs.writeFileSync` causes both an `add` and a `change` event to be fired.  Is there a way to config `sane` to only trigger the `add` event in cases like this?  I have [a repository](https://github.com/wtgtybhertgeghgtwtg/sane-add-without-change) demonstrating the issue.

**Comment by amasad** [comment]
The change is on the directory, right? You can filter the event yourself for all directory changes

**Comment by wtgtybhertgeghgtwtg** [comment]
A file is being added to the directory, which triggers an `add` event, but it is also triggering a `change` event a moment later.  I am not sure how filtering would help here.

**Comment by amasad** [comment]
I forgot about this but we do filter out all change events on [directories](https://github.com/amasad/sane/blob/697996b5ed57cd28ac9882a60a50c01f6c846f24/src/node_watcher.js#L281). I tried your repro but it didn't work for me: OS/X Node v7.2.0
