### ISSUE TITLE
Consider using Travis CI and AppVeyor.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [amasad/sane#76]
To prevent failing PR's from being merged.

**Comment by amasad** [comment]
Can you take a stab at it? I can add you as a collaborator

**Comment by wtgtybhertgeghgtwtg** [comment]
I think you have to be repository admin to set up the hooks.

**Comment by stefanpenner** [comment]
I think the current usage of `circle-ci` is sufficient.
