### ISSUE TITLE
Do not throw on missing directory/file.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [amasad/sane#87]
From [this comment](https://github.com/webpack/watchpack/pull/41#issuecomment-274165717).
Trying to watch a file that does not exist with `node_watcher` terminates the process.  `chokidar` handles this by wrapping `fs.watch` in a try-catch block and swallowing the error if it's an ENOENT or ENOTDIR.
Does something like that sound okay?

**Comment by amasad** [comment]
Expanding on what I mentioned on #88:

1. internally `watchdir` is (and should) never be called with a non-directory. 
2. If sane is called with a non-directory for a root that's an obvious user error that should be reported
3. Swallowing user errors is bad UX. Imagine if I had a typo, for example, it can be really hard to debug.
