### ISSUE TITLE
Uncaught lstat EPERM errors—potential error handling bug in node_watcher

### ISSUE THREAD

**Issue by marcello3d** [amasad/sane#89]
I have been having a problem where uncaught lstat EPERM errors are cropping up on Windows for some users when using the node watcher.

While I have not been able to reproduce the error on my own machine, I did find one potential bug that could cause the symptoms I'm seeing:

1. node_watcher's `recReaddir` function ([node_watcher.js#L338](https://github.com/amasad/sane/blob/a1271a3adc2fd6eaa72c33ad337f747c027ccb44/src/node_watcher.js#L338)) calls a library `walker`, which returns an EventEmitter
2. This emitter will emit 'error' events for lstat, readdir, and other errors: [walker.js#L52](https://github.com/daaku/nodejs-walker/blob/5d968ec87f873fa2d259f05cd2aacd2311e51a13/lib/walker.js#L52)
3. node_watcher isn't listening for `error` events on the emitter, so if/when they happen, they get thrown: [events.js#L161](https://github.com/nodejs/node/blob/master/lib/events.js#L161)

It's not clear to me what the correct behavior is in this scenario, should it be logic similar to [node_watcher.js#L223](https://github.com/amasad/sane/blob/a1271a3adc2fd6eaa72c33ad337f747c027ccb44/src/node_watcher.js#L223)?

**Comment by marcello3d** [comment]
Something like this: https://github.com/amasad/sane/compare/master...marcello3d:walker-errors?expand=1

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry for the late response.  Do your users have examples of where this error is occurring?

**Comment by joshkel** [comment]
I've run into this too. When using Facebook's Jest in watch mode, I'll sporadically get errors similar to the following:

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'F:\trunk\app\test\containers\RunNumberHandlerTest.js~RF236e5f90.TMP'
```

My diagnosis was the same as @marcello3d's (node_watcher's `recReaddir` -> 'error' event -> no `error` listener).

From what I can tell, the culprit in my case is an editor creating temporary files with ShareMode 0 (none). (See [MSDN's CreateFile docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx).) Node then attempts its own CreateFile call as part of [its lstat implementation](https://github.com/nodejs/node/blob/47f8f7462fb198aa27ede602c43786bdbfda37a2/deps/uv/src/win/fs.c#L1184), and that fails. 

I can reproduce the error by creating a file, changing the file permissions to deny access to everyone, then running Jest.

**Comment by amasad** [comment]
@joshkel || @marcello3d patches welcome :)

**Comment by joshkel** [comment]
@amasad - I'd be happy to submit a patch, but I'm not using sane directly and am really not familiar with its design.

Should it ignore errors completely, under the assumption that callers don't assume they'll have to handle errors and that there aren't any actionable events on inaccessible or erroneous files?

Should it try to special case a couple of errors for walker, [like it does for lstat](https://github.com/amasad/sane/blob/a1271a3adc2fd6eaa72c33ad337f747c027ccb44/src/node_watcher.js#L223)?

Something else?

**Comment by marcello3d** [comment]
How does my patch from up above look?

**Comment by amasad** [comment]
@marcello3d the patch looks good. But I don't understand why should we also ignore "ENOENT"? EPERM seems to be the problem here

**Comment by marcello3d** [comment]
I refactored the existing code into an new helper function, see https://github.com/amasad/sane/compare/master...marcello3d:walker-errors?expand=1#diff-18c7836cd56d6aee3a621e821c9c121fL223

As to why the existing code did that, I couldn't tell you. :-)
