### ISSUE TITLE
Consider attempting to use `watchman` before defaulting to `node`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [amasad/sane#90]
A common way of using `sane` is to try to use `watchman`, then fallback to `node` if that doesn't work.  Can that be made the default?

**Comment by amasad** [comment]
We usually keep this up to the user to decide. Changing it would be a breaking change. You can introduce a new "intelligent" watch picker but it needs to be a separate method. For research I'd check out what React Native Packager, Jest, and Ember-cli do to intelligently pick the watcher.
