### ISSUE TITLE
Consider bumping minimum supported `node` version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [amasad/sane#92]
The code base can be significantly simplified by the syntax available for `node>=4`.
At it's core, `sane` is a relatively simple library; pick one of several methods of watching the file system and normalize events to account for the differences.  However, it has several eccentric design choices that are difficult to grok, consequently raising the contribution barrier.  For example, `sane` has three files, `node_watcher`, `poll_watcher`, and `watchman_watcher`; the names would give the impression that they are the same type of thing, a watcher.  So it'd be easier to imagine that the structure is something like
1. `Watcher` extends `EventEmitter`
2. `Watcher` defines constants and functions common to watchers
3. `node_watcher`, `poll_watcher`, and `watchman_watcher` extend `Watcher`
4. `node_watcher`, `poll_watcher`, and `watchman_watcher` implement their specific functionality

But `sane` eschews this kind of inheritance model.  Instead, the it implements something like
1. Constants and functions common to watchers are defined in `common`
2. `node_watcher`, `poll_watcher`, and `watchman_watcher` extend `EventEmitter`
3. `node_watcher`, `poll_watcher`, and `watchman_watcher` use constants and functions from `common` to implement their functionality

It's not wrong, and it's certainly functional, but it's confusing, and causes a lot of duplication.  Each watcher has to specifically set up their options, resolve their root, invoke a callback on `close`; little things, but duplicated.  If you want to create a new watcher (for example, [a smart watcher that uses `watchman` is available but falls back to `node_watcher`](https://github.com/amasad/sane/issues/90#issuecomment-280228758)), you'd have to copy that again.  If you want to change something common to watchers, you have to copy that change on every watcher.

Strictly speaking, moving to a class-based structure isn't a breaking change, but it is a major rewrite; there's no better time to bump versions, if only for the simplicity the new syntax would provider (classes instead of prototype chains, Maps and Sets over objects and arrays).

Additionally, a smart watcher would use [a function that isn't available in `node@0.6.0` ](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options) and most of the dependencies no long test on `node@0.6.0`, but I've already written too much.

**Comment by stefanpenner** [comment]
I am down to say, sane should mimic node LTS policy. In practice that means, we bump major version when we drop support, and right now we can drop support for everything bellow node 6.

@amasad do you agree?

**Comment by stefanpenner** [comment]
fixed by https://github.com/amasad/sane/commit/0c439f079b320fdc85b6abe871975f1605b0392e

Will be cutting a major version bump shortly.
