### ISSUE TITLE
Add option to use graceful-fs to avoid EMFILE errors

### ISSUE THREAD

**Issue by callumlocke** [amasad/sane#96]
I've started getting EMFILE errors when using sane to watch a large directory.

Would it make a difference if sane used graceful-fs? If so, could sane add an option to use graceful-fs?

**Comment by amasad** [comment]
Which OS is this? My recommendation would be to use watchman. 
I'm not opposed to graceful-fs but it should probably be by default instead of an option.

**Comment by stefanpenner** [comment]
Closing this, will gladly reopen if @amasad's questions are answered, as at that point it becomes actionable.
